- name: Deploy Docker Container
  hosts: btj-academy
  become: true
  tasks:
    - name: Run Docker Container
      docker_container:
        name: "{{ name }}"
        image: "{{ image }}"
        state: started
        ports:
          - "80:80"
        env:
          NAME: "{{ name }}"
          IMAGE: "{{ image }}"
        detach: true
        interactive: true
        tty: true
